---
- name: Execute join Command
  script: kubernetes_join.sh
#  shell: "{{ kubernetes_workers.stdout_lines[0] }}"
##
- name: Remove file with join command after use
  file:
    path: ./kubernetes_join.sh
    state: absent
  delegate_to: localhost
  become: false
...
