---
- name: Run sample application (deployment and service)
  shell: kubectl create deploy mynginx --image=docker.io/kodmandvl/mynginx:v5 --replicas=2 ; kubectl expose deployment mynginx --port=8000 --target-port=8080
...
